global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sus-connect-network-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
